
- input_format: 'tool description:
    {{tool_desc}}'
  model: openrouter/anthropic/claude-3-sonnet
  prompt_name: indietool_categorize_pattern
  output_name: tool_categories

- input_format: 'markdown content:

    {{tool_desc}}

    categories and tags:

    {{tool_categories}}'
  model: openrouter/anthropic/claude-3-sonnet
  prompt_name: indietool_json_pattern
  output_name: tool_json 