# 工具收集工作流，输入链接，生成 markdown

strategies:
- input_format: 'url: {{text}}'
  tool_name: jina_reader
  tool_params:
    retain_images: false
    with_links_summary: true
  output_name: website_info

- input_format: '{{text}}'
  tool_name: exa_search
  tool_params:
    num_results: 10
    category: tweet
  output_name: search_results

- input_format: 'website info:

    {{website_info}}

    search results:

    {{search_results}}'
  model: openrouter/anthropic/claude-3-sonnet
  prompt_name: indietool_desc_pattern
  output_name: tool_desc

- input_format: '{{tool_desc}}'
  tool_name: save_to_indieto
  tool_params:
    link: "{{text}}"
  output_name: save_result